#!/usr/bin/env tsx
/**
 * Nightly staleness report.
 *
 * For each OWNER-SPEC:
 *   1. Age check: last_attested + max_unattested_days < now() AND tool dir has commits since last_attested
 *   2. Coupling check: any couples_with path has been modified since last_attested
 *
 * Writes findings to docs/audits/derived/_owner-spec-staleness.{json,md}.
 * Surfaces on the status page under /derive alongside other derived health.
 */

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { findOwnerSpecs, parseOwnerSpec, relativeFromRepoRoot } from './parse.js';
import type { StalenessFinding } from './types.js';

const REPO_ROOT = process.cwd();
const OUTPUT_DIR = join(REPO_ROOT, 'docs', 'audits', 'derived');

function commitsSince(path: string, sinceISO: string): number {
  try {
    const out = execSync(`git log --oneline --since="${sinceISO}" -- "${path}"`, {
      encoding: 'utf-8',
    });
    return out.split('\n').filter(Boolean).length;
  } catch {
    return 0;
  }
}

function daysSince(isoDate: string): number {
  const then = new Date(isoDate + 'T00:00:00Z').getTime();
  const now = Date.now();
  return Math.floor((now - then) / (1000 * 60 * 60 * 24));
}

function main(): void {
  const specPaths = findOwnerSpecs();
  const findings: StalenessFinding[] = [];

  for (const specPath of specPaths) {
    const spec = parseOwnerSpec(specPath);
    if (!spec) continue;

    const specRel = relativeFromRepoRoot(spec.path);
    const toolDirRel = relativeFromRepoRoot(spec.toolDir);
    const ageDays = daysSince(spec.frontmatter.last_attested);

    // 1. Age + tool-churn check
    if (ageDays >= spec.frontmatter.max_unattested_days) {
      const churn = commitsSince(toolDirRel, spec.frontmatter.last_attested);
      if (churn > 0) {
        findings.push({
          tool: spec.frontmatter.tool,
          spec_path: specRel,
          reason: 'age',
          detail: `Last attested ${ageDays} days ago (limit ${spec.frontmatter.max_unattested_days}); ${churn} commits to ${toolDirRel} since then.`,
          age_days: ageDays,
        });
      }
    }

    // 2. Coupling check — any couples_with path modified since last_attested
    const coupling_changes: string[] = [];
    for (const couple of spec.frontmatter.couples_with) {
      const churn = commitsSince(couple, spec.frontmatter.last_attested);
      if (churn > 0) coupling_changes.push(`${couple} (${churn} commits)`);
    }
    if (coupling_changes.length > 0) {
      findings.push({
        tool: spec.frontmatter.tool,
        spec_path: specRel,
        reason: 'coupling',
        detail: `Coupled paths modified since last_attested: ${coupling_changes.join(', ')}`,
        coupling_changes,
      });
    }
  }

  // Write JSON
  if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });
  const json = {
    derived_at: new Date().toISOString(),
    findings,
    summary: {
      total_specs: specPaths.length,
      stale_count: findings.length,
      age_count: findings.filter((f) => f.reason === 'age').length,
      coupling_count: findings.filter((f) => f.reason === 'coupling').length,
    },
  };
  writeFileSync(join(OUTPUT_DIR, '_owner-spec-staleness.json'), JSON.stringify(json, null, 2) + '\n');

  // Write Markdown
  const md = renderMarkdown(json);
  writeFileSync(join(OUTPUT_DIR, '_owner-spec-staleness.md'), md);

  // Console summary
  console.log(`[owner-spec-lint:staleness] ${specPaths.length} OWNER-SPECs scanned, ${findings.length} findings`);
  for (const f of findings) {
    console.log(`  - ${f.tool}: ${f.reason} — ${f.detail}`);
  }

  // Exit 0; staleness is a report, not a gate
  process.exit(0);
}

function renderMarkdown(json: ReturnType<typeof buildJsonForRender>): string {
  let md = '';
  md += '---\n';
  md += 'canonical: false\n';
  md += 'derives_from:\n';
  md += '  - tools/owner-spec-lint/staleness.ts\n';
  md += `derived_at: ${json.derived_at}\n`;
  md += '---\n\n';
  md += '# OWNER-SPEC staleness report\n\n';
  md += '> Auto-generated by `tools/owner-spec-lint`. Do not edit by hand.\n';
  md += '> See [`docs/methodology/owner-spec-convention.md`](../../methodology/owner-spec-convention.md) for the convention.\n\n';
  md += `- **scanned:** ${json.summary.total_specs}\n`;
  md += `- **stale (any reason):** ${json.summary.stale_count}\n`;
  md += `- **age-based:** ${json.summary.age_count}\n`;
  md += `- **coupling-based:** ${json.summary.coupling_count}\n\n`;
  if (json.findings.length === 0) {
    md += '## All OWNER-SPECs fresh\n\nNo staleness findings.\n';
    return md;
  }
  md += '## Findings\n\n';
  md += '| Tool | Reason | Detail | Spec |\n';
  md += '|---|---|---|---|\n';
  for (const f of json.findings) {
    md += `| \`${f.tool}\` | ${f.reason} | ${f.detail.replace(/\|/g, '\\|')} | \`${f.spec_path}\` |\n`;
  }
  md += '\n## Re-attestation\n\n';
  md += 'When the operator confirms an OWNER-SPEC is still accurate, bump `last_attested:` in its frontmatter to today\'s date. If the spec is no longer accurate, update the relevant sections first, then bump the date.\n';
  return md;
}

// Helper just to type-narrow the render fn input
function buildJsonForRender() {
  return {
    derived_at: '',
    findings: [] as StalenessFinding[],
    summary: { total_specs: 0, stale_count: 0, age_count: 0, coupling_count: 0 },
  };
}

main();
