import { writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import type { CapabilityCategory, State } from './types.ts';

export function getCommitSha(repoRoot: string): string {
  try {
    return execSync('git rev-parse HEAD', { cwd: repoRoot, encoding: 'utf-8' }).trim();
  } catch {
    return 'unknown';
  }
}

export function getCommitSubject(repoRoot: string, sha: string): string {
  try {
    return execSync(`git log -1 --pretty=%s ${sha}`, { cwd: repoRoot, encoding: 'utf-8' }).trim();
  } catch {
    return '';
  }
}

export function writeJson(outPath: string, state: State): void {
  writeFileSync(outPath, JSON.stringify(state, null, 2) + '\n', 'utf-8');
}

function statusEmoji(status: string): string {
  switch (status) {
    case 'COMPLIANT':
      return '[OK]';
    case 'PARTIAL':
      return '[~~]';
    case 'NON-COMPLIANT':
      return '[XX]';
    case 'ABSENT':
      return '[--]';
    case 'ERROR':
      return '[!!]';
    case 'MANUAL_REVIEW':
      return '[??]';
    default:
      return '[??]';
  }
}

const CATEGORY_LABELS: Record<CapabilityCategory, string> = {
  capability: 'Capabilities',
  convention: 'Conventions',
  'adr-commitment': 'ADR Commitments',
  feature_flag_inactive: 'Feature Flag Retirement',
  'scenario-coverage': 'Scenario Coverage',
};

export function renderMarkdown(state: State, repoRoot: string, projectName = 'project'): string {
  const subject = getCommitSubject(repoRoot, state.as_of_commit);
  const lines: string[] = [];
  lines.push('---');
  lines.push('canonical: false');
  lines.push('derives_from:');
  lines.push('  - tools/state-derive/catalog');
  lines.push(`as_of_commit: ${state.as_of_commit.slice(0, 7)}`);
  lines.push('staleness_threshold_days: 1');
  lines.push('---');
  lines.push('');
  lines.push(`# ${projectName} implementation state`);
  lines.push('');
  lines.push('> **Auto-generated by `tools/state-derive`.** Do not edit by hand.');
  lines.push('> Re-run with `cd tools/state-derive && npm run derive`.');
  lines.push('');
  lines.push(`- **as_of_commit:** \`${state.as_of_commit.slice(0, 7)}\` — ${subject}`);
  lines.push(`- **generated_at:** ${state.generated_at}`);
  lines.push(`- **schema_version:** ${state.schema_version}`);
  lines.push(`- **capabilities checked:** ${state.capabilities.length}`);
  lines.push('');

  const summary = state.capabilities.reduce<Record<string, number>>((acc, c) => {
    acc[c.status] = (acc[c.status] ?? 0) + 1;
    return acc;
  }, {});
  lines.push('## Summary');
  lines.push('');
  lines.push('| Status | Count |');
  lines.push('|--------|------:|');
  for (const status of ['COMPLIANT', 'PARTIAL', 'NON-COMPLIANT', 'ABSENT', 'ERROR', 'MANUAL_REVIEW']) {
    if (summary[status]) {
      lines.push(`| ${statusEmoji(status)} ${status} | ${summary[status]} |`);
    }
  }
  lines.push('');

  const byCategory = new Map<CapabilityCategory, typeof state.capabilities>();
  for (const c of state.capabilities) {
    const cat = c.capability.category;
    const arr = byCategory.get(cat) ?? [];
    arr.push(c);
    byCategory.set(cat, arr);
  }

  for (const [cat, items] of byCategory) {
    lines.push(`## ${CATEGORY_LABELS[cat] ?? cat}`);
    lines.push('');
    lines.push('| ID | Status | Description |');
    lines.push('|----|--------|-------------|');
    for (const c of items) {
      lines.push(
        `| \`${c.capability.id}\` | ${statusEmoji(c.status)} ${c.status} | ${c.capability.description} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Evidence detail');
  lines.push('');
  for (const c of state.capabilities) {
    lines.push(`<details>`);
    lines.push(
      `<summary><code>${c.capability.id}</code> — ${statusEmoji(c.status)} ${c.status} — ${c.capability.description}</summary>`,
    );
    lines.push('');
    if (c.capability.manual_review) {
      lines.push(`> **MANUAL REVIEW REQUIRED** — this capability cannot be fully verified mechanically.`);
      lines.push('');
    }
    if (c.capability.reference) {
      lines.push(`*Reference:* ${c.capability.reference}`);
      lines.push('');
    }
    if (c.capability.notes) {
      lines.push(`*Notes:* ${c.capability.notes}`);
      lines.push('');
    }
    for (const r of c.results) {
      const verdict = r.error ? 'ERROR' : r.matched ? 'OK' : 'FAIL';
      lines.push(`**${verdict} — ${r.check.type}**${r.check.description ? ': ' + r.check.description : ''}`);
      lines.push('');
      lines.push('```');
      if (r.error) lines.push(`error: ${r.error}`);
      for (const e of r.evidence) lines.push(e);
      lines.push('```');
      lines.push('');
    }
    lines.push(`</details>`);
    lines.push('');
  }

  return lines.join('\n');
}

export function writeMarkdown(
  outPath: string,
  state: State,
  repoRoot: string,
  projectName?: string,
): void {
  writeFileSync(outPath, renderMarkdown(state, repoRoot, projectName), 'utf-8');
}
